sudo: required 
language: node_js
node_js:
  - "node"
services:
  - docker


before_install:
  - docker build -t faizanadil/docker -f Dockerfile.dev . 


script:
  - docker run faizanadil/docker npm run test -- --coverage