sudo: required 
language: node_js
node_js:
  - "node"
services:
  - docker


before_install:
  - docker build -t faizanadil/docker -f Dockerfile.dev . 
  
 install: travis_wait 30 mvn install

script:
  - docker run faizanadil/docker npm run test -- --coverage